### ISSUE TITLE
Hi, Its not very clear to me how I can read the list of posts.

### ISSUE THREAD

**Issue by waelsaad** [SK8-PTY-LTD/WPAPI_iOS#1]
https://github.com/SK8-PTY-LTD/WPAPI_iOS/blob/2255ed7ada3ab631dbbe7e4e4a7d64f080b3fc2a/WPAPI/Classes/WPRestEndpoint.swift#L9

Hi, This is a really great Juicy frame work for working with WordPress which is what I am working on now. I just have couple of questions to get me started and I would really appreciate your help.

I am just trying to do something simple like read the posts for a site : 
https://demo.wp-api.org/wp-json/wp/v2

1- I suppose we need to uncomment this file out but when I do so it complains : No such module 'Alamofire' but Alamofire is required for the HTTPMethod. So how do I get the pod to use the Alamofire pod?

2- How do I actually make the call from the example project just to read the posts of a site is there a usage somewhere?

Thank you,

Wael

**Comment by jacktator** [comment]
@waelsaad Thank you for your message.

Totally agree with you, we HAVE to spend more time to write up the docs.

Answering your questions,

This framework is written using Swift 4, fully leveraging Codable class, avoiding the overhead brought by Alamofire. The line you pointed out was from our legacy code, I'll remove in the very near future. 

1. This file is a legacy file, do not uncomment. 
2. In order to run the sample, you need to udpate the URL here:
https://github.com/SK8-PTY-LTD/WPAPI_iOS/blob/2255ed7ada3ab631dbbe7e4e4a7d64f080b3fc2a/Example/WPAPI/AppDelegate.swift#L21

I will try to update README ASAP.

**Comment by jacktator** [comment]
@waelsaad I saw a bright future in WordPress, and especially its potential to be used as a full bloom backend solution, which is why we've also written 3 plugins to extend its REST API capabilities:
https://github.com/SK8-PTY-LTD/wp-rest-user
https://github.com/SK8-PTY-LTD/wp-rest-filter
https://github.com/SK8-PTY-LTD/wc-rest-payment

The reason I started this Pod was that I wanted an easy to use SDK ish Pod so my iOS app can write less code.

However, I'm not too sure about the future of writing a CocoaPods targeting Swift though, given that lots of devs are moving towards ReactNative. 

What do you think? Is it worth the while to further develop this?

**Comment by waelsaad** [comment]
@jacktator Thank you for the prompt response and apology for the delay, I was occupied with work, I am working as an iOS Developer and yes I understand there is a big move to ReactNative however there is no way it will beat creating native apps thats my personal humble view. My dream is to use Swift for both platforms Android and iOS.

I am starting a personal none profit project on the side to query WordPress not necessarily to use it as a full backend solution but I liked your API because it is very comprehensive so I am learning how to use it.

So I believe it is important keep this WPAPI_iOS under development.

**Comment by waelsaad** [comment]
@jacktator one thing in my opinion needs to change is to remove the crud operations from the model files, so they need to be in their own services files (i.e need to decouple the save, get, delete, etc...) away from the each class.

What do you think?

**Comment by waelsaad** [comment]
@jacktator why is the library model is missing one of the main rest API calls which is the ability to retrieve pages and its contents. Is it intentional?

**Comment by jacktator** [comment]
@waelsaad Thank you for the comment. 

We started this lib to help us develop internal projects. For the websites we develop, we use shortcode in pages. And we thought most pages are done that way.

When retrieving pages, if it return shortcodes, it make no much sense. Therefore it wasn't prioritized. 

Are you looking to retrieve pages?

**Comment by waelsaad** [comment]
@jacktator yes I am and display their content also. I think still it would be good to integrate such functionality instead of manually implementing this as it is an important API that will be required by many Apps to display content from WordPress.

**Comment by jacktator** [comment]
@waelsaad I'll get it added hopefully within this week.

**Comment by waelsaad** [comment]
@jacktator Hi Jack, I hope you have a chance to add retrieving content also so I can start utilizing this API properly. I think you'll need to generate Content.swift or Pages.swift into the model right ! Thanks

**Comment by waelsaad** [comment]
@jacktator also I think the model for each entity is too large, I hope there is a way to have generic CRUD methods for each of the entities as oppose to repeating these in every file and the only difference is maybe a line or 2 lines of code, its just a thought.

**Comment by jacktator** [comment]
@waelsaad Hi, I've added Page.swift. See if it works for you.

Also, thank you for your suggestion.

**Comment by waelsaad** [comment]
@jacktator Thank you, your the best now I am able to retrieve content I will continue with my development and see how it goes, I will be touching base every now and then as I'll be using your API. Thank you.

**Comment by jacktator** [comment]
All good mate
